// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_file_name_index from "./routes/api/file/[name]/index.ts";
import * as $index from "./routes/index.tsx";
import * as $BackgroundGradient from "./islands/BackgroundGradient.tsx";
import * as $ProjectCard from "./islands/ProjectCard.tsx";
import * as $Video from "./islands/Video.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/file/[name]/index.ts": $api_file_name_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BackgroundGradient.tsx": $BackgroundGradient,
    "./islands/ProjectCard.tsx": $ProjectCard,
    "./islands/Video.tsx": $Video,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
